import StyledProvider from "@/lib/StyledProvider";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <html lang="ko">
        <body>
          <StyledProvider>
            <header>header</header>

            {children}

            <footer>footer</footer>
          </StyledProvider>

          <Analytics />
          <SpeedInsights />
        </body>
      </html>
    </>
  );
};

export default RootLayout;
