import StyledProvider from "@/lib/StyledProvider";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <Analytics />
      <SpeedInsights />

      <html lang="ko">
        <body>
          <StyledProvider>{children}</StyledProvider>
        </body>
      </html>
    </>
  );
};

export default RootLayout;
